
package org.webservices.orderprocess;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "OrderProcessImplService", targetNamespace = "http://OrderProcess.WebServices.org", wsdlLocation = "http://localhost:8080/OrderProcessWService/services/OrderProcessImpl?wsdl")
public class OrderProcessImplService
    extends Service
{

    private final static URL ORDERPROCESSIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException ORDERPROCESSIMPLSERVICE_EXCEPTION;
    private final static QName ORDERPROCESSIMPLSERVICE_QNAME = new QName("http://OrderProcess.WebServices.org", "OrderProcessImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/OrderProcessWService/services/OrderProcessImpl?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ORDERPROCESSIMPLSERVICE_WSDL_LOCATION = url;
        ORDERPROCESSIMPLSERVICE_EXCEPTION = e;
    }

    public OrderProcessImplService() {
        super(__getWsdlLocation(), ORDERPROCESSIMPLSERVICE_QNAME);
    }

    public OrderProcessImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ORDERPROCESSIMPLSERVICE_QNAME, features);
    }

    public OrderProcessImplService(URL wsdlLocation) {
        super(wsdlLocation, ORDERPROCESSIMPLSERVICE_QNAME);
    }

    public OrderProcessImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ORDERPROCESSIMPLSERVICE_QNAME, features);
    }

    public OrderProcessImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OrderProcessImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns OrderProcessImpl
     */
    @WebEndpoint(name = "OrderProcessImpl")
    public OrderProcessImpl getOrderProcessImpl() {
        return super.getPort(new QName("http://OrderProcess.WebServices.org", "OrderProcessImpl"), OrderProcessImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OrderProcessImpl
     */
    @WebEndpoint(name = "OrderProcessImpl")
    public OrderProcessImpl getOrderProcessImpl(WebServiceFeature... features) {
        return super.getPort(new QName("http://OrderProcess.WebServices.org", "OrderProcessImpl"), OrderProcessImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ORDERPROCESSIMPLSERVICE_EXCEPTION!= null) {
            throw ORDERPROCESSIMPLSERVICE_EXCEPTION;
        }
        return ORDERPROCESSIMPLSERVICE_WSDL_LOCATION;
    }

}
