
package org.webservices.orderprocess;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "OrderProcessImpl", targetNamespace = "http://OrderProcess.WebServices.org")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface OrderProcessImpl {


    /**
     * 
     * @param accountName
     * @param accountPassword
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(name = "getAccountReturn", targetNamespace = "http://OrderProcess.WebServices.org")
    @RequestWrapper(localName = "getAccount", targetNamespace = "http://OrderProcess.WebServices.org", className = "org.webservices.orderprocess.GetAccount")
    @ResponseWrapper(localName = "getAccountResponse", targetNamespace = "http://OrderProcess.WebServices.org", className = "org.webservices.orderprocess.GetAccountResponse")
    public List<String> getAccount(
        @WebParam(name = "accountName", targetNamespace = "http://OrderProcess.WebServices.org")
        String accountName,
        @WebParam(name = "accountPassword", targetNamespace = "http://OrderProcess.WebServices.org")
        String accountPassword);

    /**
     * 
     * @param total
     * @param shippingId
     * @param customerId
     * @param tax
     * @param status
     * @param orderDate
     * @param grandTotal
     * @param shippingCost
     * @param billingId
     * @param orderId
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(name = "createOrderReturn", targetNamespace = "http://OrderProcess.WebServices.org")
    @RequestWrapper(localName = "createOrder", targetNamespace = "http://OrderProcess.WebServices.org", className = "org.webservices.orderprocess.CreateOrder")
    @ResponseWrapper(localName = "createOrderResponse", targetNamespace = "http://OrderProcess.WebServices.org", className = "org.webservices.orderprocess.CreateOrderResponse")
    public boolean createOrder(
        @WebParam(name = "order_id", targetNamespace = "http://OrderProcess.WebServices.org")
        int orderId,
        @WebParam(name = "customer_id", targetNamespace = "http://OrderProcess.WebServices.org")
        int customerId,
        @WebParam(name = "shipping_id", targetNamespace = "http://OrderProcess.WebServices.org")
        int shippingId,
        @WebParam(name = "billing_id", targetNamespace = "http://OrderProcess.WebServices.org")
        int billingId,
        @WebParam(name = "order_date", targetNamespace = "http://OrderProcess.WebServices.org")
        String orderDate,
        @WebParam(name = "total", targetNamespace = "http://OrderProcess.WebServices.org")
        int total,
        @WebParam(name = "shipping_cost", targetNamespace = "http://OrderProcess.WebServices.org")
        int shippingCost,
        @WebParam(name = "tax", targetNamespace = "http://OrderProcess.WebServices.org")
        int tax,
        @WebParam(name = "grand_total", targetNamespace = "http://OrderProcess.WebServices.org")
        int grandTotal,
        @WebParam(name = "status", targetNamespace = "http://OrderProcess.WebServices.org")
        String status);

    /**
     * 
     * @param lateAccessed
     * @param customerId
     * @param attempts
     * @param dateCreated
     * @param login
     * @param password
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(name = "createAccountReturn", targetNamespace = "http://OrderProcess.WebServices.org")
    @RequestWrapper(localName = "createAccount", targetNamespace = "http://OrderProcess.WebServices.org", className = "org.webservices.orderprocess.CreateAccount")
    @ResponseWrapper(localName = "createAccountResponse", targetNamespace = "http://OrderProcess.WebServices.org", className = "org.webservices.orderprocess.CreateAccountResponse")
    public boolean createAccount(
        @WebParam(name = "login", targetNamespace = "http://OrderProcess.WebServices.org")
        String login,
        @WebParam(name = "password", targetNamespace = "http://OrderProcess.WebServices.org")
        String password,
        @WebParam(name = "customer_id", targetNamespace = "http://OrderProcess.WebServices.org")
        int customerId,
        @WebParam(name = "date_created", targetNamespace = "http://OrderProcess.WebServices.org")
        String dateCreated,
        @WebParam(name = "late_accessed", targetNamespace = "http://OrderProcess.WebServices.org")
        String lateAccessed,
        @WebParam(name = "attempts", targetNamespace = "http://OrderProcess.WebServices.org")
        int attempts);

    /**
     * 
     * @param status
     * @param orderId
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(name = "confirmOrderReturn", targetNamespace = "http://OrderProcess.WebServices.org")
    @RequestWrapper(localName = "confirmOrder", targetNamespace = "http://OrderProcess.WebServices.org", className = "org.webservices.orderprocess.ConfirmOrder")
    @ResponseWrapper(localName = "confirmOrderResponse", targetNamespace = "http://OrderProcess.WebServices.org", className = "org.webservices.orderprocess.ConfirmOrderResponse")
    public boolean confirmOrder(
        @WebParam(name = "order_id", targetNamespace = "http://OrderProcess.WebServices.org")
        String orderId,
        @WebParam(name = "status", targetNamespace = "http://OrderProcess.WebServices.org")
        String status);

}
